In [36]:
import pandas as pd

In [37]:
path = "C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets"

In [38]:
path + "/good.json"

'C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets/good.json'

In [39]:
df = pd.read_json(path + "/good.json")
df

                                       audio_features
0   {'danceability': 0.749, 'energy': 0.839, 'key'...
1   {'danceability': 0.5730000000000001, 'energy':...
2   {'danceability': 0.8, 'energy': 0.719, 'key': ...
3   {'danceability': 0.778, 'energy': 0.632, 'key'...
4   {'danceability': 0.797, 'energy': 0.852, 'key'...
..                                                ...
95  {'danceability': 0.616, 'energy': 0.534, 'key'...
96  {'danceability': 0.802, 'energy': 0.549, 'key'...
97  {'danceability': 0.767, 'energy': 0.659, 'key'...
98  {'danceability': 0.752, 'energy': 0.468, 'key'...
99  {'danceability': 0.797, 'energy': 0.654, 'key'...

[100 rows x 1 columns]

In [40]:
df_musics = pd.json_normalize(df["audio_features"])
df_musics

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,type,id,uri,track_href,analysis_url,duration_ms,time_signature
0,0.749,0.839,6,-4.847,1,0.2970,0.0867,0.000000,0.2040,0.804,172.068,audio_features,55mcupbf7cIsuCEVAuTJVk,spotify:track:55mcupbf7cIsuCEVAuTJVk,https://api.spotify.com/v1/tracks/55mcupbf7cIs...,https://api.spotify.com/v1/audio-analysis/55mc...,111000,4
1,0.573,0.581,10,-9.026,0,0.3390,0.7530,0.000001,0.1300,0.351,76.506,audio_features,57RtLWT7IpugV0yi5bsxJk,spotify:track:57RtLWT7IpugV0yi5bsxJk,https://api.spotify.com/v1/tracks/57RtLWT7Ipug...,https://api.spotify.com/v1/audio-analysis/57Rt...,169347,4
2,0.800,0.719,7,-6.262,1,0.2340,0.1090,0.000000,0.0580,0.815,143.975,audio_features,5VyfAfp2Yt3qaeuvq55ll3,spotify:track:5VyfAfp2Yt3qaeuvq55ll3,https://api.spotify.com/v1/tracks/5VyfAfp2Yt3q...,https://api.spotify.com/v1/audio-analysis/5Vyf...,230854,4
3,0.778,0.632,8,-6.415,1,0.1250,0.0404,0.000000,0.0912,0.827,140.951,audio_features,3eWHY75nDgte70hh5yf4UW,spotify:track:3eWHY75nDgte70hh5yf4UW,https://api.spotify.com/v1/tracks/3eWHY75nDgte...,https://api.spotify.com/v1/audio-analysis/3eWH...,224029,4
4,0.797,0.852,8,-5.202,1,0.2410,0.0555,0.000024,0.0536,0.480,136.035,audio_features,2UwrB6Ge6mPfUV8yGvAfX7,spotify:track:2UwrB6Ge6mPfUV8yGvAfX7,https://api.spotify.com/v1/tracks/2UwrB6Ge6mPf...,https://api.spotify.com/v1/audio-analysis/2Uwr...,102353,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.616,0.534,10,-10.264,0,0.4830,0.6390,0.000000,0.0844,0.556,170.054,audio_features,3dl4lXWlOxnGo94OqNtpdq,spotify:track:3dl4lXWlOxnGo94OqNtpdq,https://api.spotify.com/v1/tracks/3dl4lXWlOxnG...,https://api.spotify.com/v1/audio-analysis/3dl4...,146480,4
96,0.802,0.549,5,-8.600,0,0.0631,0.2680,0.004960,0.0984,0.498,138.984,audio_features,3DWDcsDoXRIFynCREIkibM,spotify:track:3DWDcsDoXRIFynCREIkibM,https://api.spotify.com/v1/tracks/3DWDcsDoXRIF...,https://api.spotify.com/v1/audio-analysis/3DWD...,184627,4
97,0.767,0.659,7,-4.541,1,0.0387,0.7850,0.000000,0.1120,0.631,90.056,audio_features,6fmtZEUoGwxPNvUgr0NJm1,spotify:track:6fmtZEUoGwxPNvUgr0NJm1,https://api.spotify.com/v1/tracks/6fmtZEUoGwxP...,https://api.spotify.com/v1/audio-analysis/6fmt...,186720,4
98,0.752,0.468,0,-9.966,1,0.3330,0.8050,0.000000,0.1360,0.716,82.795,audio_features,2edc1m7WXxdBA61WlxSInp,spotify:track:2edc1m7WXxdBA61WlxSInp,https://api.spotify.com/v1/tracks/2edc1m7WXxdB...,https://api.spotify.com/v1/audio-analysis/2edc...,179253,4
99,0.797,0.654,8,-7.373,1,0.2450,0.6330,0.000000,0.1060,0.640,145.121,audio_features,3qjDXaWCalJ9ZzaHBG4j3V,spotify:track:3qjDXaWCalJ9ZzaHBG4j3V,https://api.spotify.com/v1/tracks/3qjDXaWCalJ9...,https://api.spotify.com/v1/audio-analysis/3qjD...,172520,4

In [41]:
df_musics.dtypes

danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
type                 object
id                   object
uri                  object
track_href           object
analysis_url         object
duration_ms           int64
time_signature        int64
dtype: object

In [42]:
df_musics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   danceability      100 non-null    float64
 1   energy            100 non-null    float64
 2   key               100 non-null    int64
 3   loudness          100 non-null    float64
 4   mode              100 non-null    int64
 5   speechiness       100 non-null    float64
 6   acousticness      100 non-null    float64
 7   instrumentalness  100 non-null    float64
 8   liveness          100 non-null    float64
 9   valence           100 non-null    float64
 10  tempo             100 non-null    float64
 11  type              100 non-null    object
 12  id                100 non-null    object
 13  uri               100 non-null    object
 14  track_href        100 non-null    object
 15  analysis_url      100 non-null    object
 16  duration_ms       100 non-null    int64
 17  time_signature    100 non-null    int64
dtypes: float64(9), int64(4), object(5)
memory usage: 14.2+ KB

In [43]:
path + "/athletes.csv"

'C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets/athletes.csv'

In [44]:
df_athletes = pd.read_csv(path + "/athletes.csv")
df_athletes

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,JOSEPH E,Elijah JOSEPH,Male,Athlete,TTO,Trinidad and Tobago,Trinidad and Tobago,Trinidad and Tobago,...,NaN,English,Personal: Ebert Joseph (TTO),NaN,NaN,NaN,NaN,NaN,NaN,NaN
11106,4982762,HOMAN Khrystyna,HOMAN K,Khrystyna HOMAN,Female,Athlete,UKR,Ukraine,Ukraine,Ukraine,...,Mother and one younger brother,Ukrainian,National: Quedjau Nhabali (UKR).<br>Personal: ...,Because her mother raised the idea,NaN,"""Quedjau Nhabali is always there with the righ...",NaN,NaN,NaN,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,CHELANGAT AC,Annet Chemengich CHELANGAT,Female,Athlete,UGA,Uganda,Uganda,Uganda,...,NaN,English,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11108,4986655,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,NaN,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df_athletes.dtypes

code                    int64
name                   object
name_short             object
name_tv                object
gender                 object
function               object
country_code           object
country                object
country_full           object
nationality            object
nationality_full       object
nationality_code       object
height                  int64
weight                float64
disciplines            object
events                 object
birth_date             object
birth_place            object
birth_country          object
residence_place        object
residence_country      object
nickname               object
hobbies                object
occupation             object
education              object
family                 object
lang                   object
coach                  object
reason                 object
hero                   object
influence              object
philosophy             object
sporting_relatives     object
ritual                 object
other_sports           object
dtype: object

In [46]:
df_athletes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11110 entries, 0 to 11109
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   code                11110 non-null  int64
 1   name                11110 non-null  object
 2   name_short          11110 non-null  object
 3   name_tv             11110 non-null  object
 4   gender              11110 non-null  object
 5   function            11110 non-null  object
 6   country_code        11110 non-null  object
 7   country             11110 non-null  object
 8   country_full        11110 non-null  object
 9   nationality         11091 non-null  object
 10  nationality_full    11091 non-null  object
 11  nationality_code    11091 non-null  object
 12  height              11110 non-null  int64
 13  weight              11092 non-null  float64
 14  disciplines         11110 non-null  object
 15  events              11110 non-null  object
 16  birth_date          11110 non-null  object
 17  birth_place         8713 non-null   object
 18  birth_country       9461 non-null   object
 19  residence_place     6792 non-null   object
 20  residence_country   8276 non-null   object
 21  nickname            2963 non-null   object
 22  hobbies             4201 non-null   object
 23  occupation          9571 non-null   object
 24  education           5531 non-null   object
 25  family              5555 non-null   object
 26  lang                10588 non-null  object
 27  coach               8212 non-null   object
 28  reason              5838 non-null   object
 29  hero                3312 non-null   object
 30  influence           2151 non-null   object
 31  philosophy          2779 non-null   object
 32  sporting_relatives  2516 non-null   object
 33  ritual              856 non-null    object
 34  other_sports        1057 non-null   object
dtypes: float64(1), int64(2), object(32)
memory usage: 3.0+ MB

In [47]:
df_athletes["code"].astype(str)

0        1532872
1        1532873
2        1532874
3        1532944
4        1532945
          ...
11105    4982175
11106    4982762
11107    4983537
11108    4986655
11109    9460001
Name: code, Length: 11110, dtype: object

In [48]:
pd.to_datetime(df_athletes["birth_date"])

0       1991-10-21
1       1999-01-22
2       1996-12-21
3       1999-11-22
4       1999-10-27
           ...
11105   2001-07-03
11106   1999-01-31
11107   1993-07-29
11108   2003-06-11
11109   2000-04-27
Name: birth_date, Length: 11110, dtype: datetime64[ns]