In [1]:
import pandas as pd

In [2]:
path = "C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets"

In [3]:
path + "/good.json"

'C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets/good.json'

In [4]:
df = pd.read_json(path + "/good.json")
df

                                       audio_features
0   {'danceability': 0.749, 'energy': 0.839, 'key'...
1   {'danceability': 0.5730000000000001, 'energy':...
2   {'danceability': 0.8, 'energy': 0.719, 'key': ...
3   {'danceability': 0.778, 'energy': 0.632, 'key'...
4   {'danceability': 0.797, 'energy': 0.852, 'key'...
..                                                ...
95  {'danceability': 0.616, 'energy': 0.534, 'key'...
96  {'danceability': 0.802, 'energy': 0.549, 'key'...
97  {'danceability': 0.767, 'energy': 0.659, 'key'...
98  {'danceability': 0.752, 'energy': 0.468, 'key'...
99  {'danceability': 0.797, 'energy': 0.654, 'key'...

[100 rows x 1 columns]

In [5]:
df_musics = pd.json_normalize(df["audio_features"])
df_musics

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,type,id,uri,track_href,analysis_url,duration_ms,time_signature
0,0.749,0.839,6,-4.847,1,0.2970,0.0867,0.000000,0.2040,0.804,172.068,audio_features,55mcupbf7cIsuCEVAuTJVk,spotify:track:55mcupbf7cIsuCEVAuTJVk,https://api.spotify.com/v1/tracks/55mcupbf7cIs...,https://api.spotify.com/v1/audio-analysis/55mc...,111000,4
1,0.573,0.581,10,-9.026,0,0.3390,0.7530,0.000001,0.1300,0.351,76.506,audio_features,57RtLWT7IpugV0yi5bsxJk,spotify:track:57RtLWT7IpugV0yi5bsxJk,https://api.spotify.com/v1/tracks/57RtLWT7Ipug...,https://api.spotify.com/v1/audio-analysis/57Rt...,169347,4
2,0.800,0.719,7,-6.262,1,0.2340,0.1090,0.000000,0.0580,0.815,143.975,audio_features,5VyfAfp2Yt3qaeuvq55ll3,spotify:track:5VyfAfp2Yt3qaeuvq55ll3,https://api.spotify.com/v1/tracks/5VyfAfp2Yt3q...,https://api.spotify.com/v1/audio-analysis/5Vyf...,230854,4
3,0.778,0.632,8,-6.415,1,0.1250,0.0404,0.000000,0.0912,0.827,140.951,audio_features,3eWHY75nDgte70hh5yf4UW,spotify:track:3eWHY75nDgte70hh5yf4UW,https://api.spotify.com/v1/tracks/3eWHY75nDgte...,https://api.spotify.com/v1/audio-analysis/3eWH...,224029,4
4,0.797,0.852,8,-5.202,1,0.2410,0.0555,0.000024,0.0536,0.480,136.035,audio_features,2UwrB6Ge6mPfUV8yGvAfX7,spotify:track:2UwrB6Ge6mPfUV8yGvAfX7,https://api.spotify.com/v1/tracks/2UwrB6Ge6mPf...,https://api.spotify.com/v1/audio-analysis/2Uwr...,102353,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.616,0.534,10,-10.264,0,0.4830,0.6390,0.000000,0.0844,0.556,170.054,audio_features,3dl4lXWlOxnGo94OqNtpdq,spotify:track:3dl4lXWlOxnGo94OqNtpdq,https://api.spotify.com/v1/tracks/3dl4lXWlOxnG...,https://api.spotify.com/v1/audio-analysis/3dl4...,146480,4
96,0.802,0.549,5,-8.600,0,0.0631,0.2680,0.004960,0.0984,0.498,138.984,audio_features,3DWDcsDoXRIFynCREIkibM,spotify:track:3DWDcsDoXRIFynCREIkibM,https://api.spotify.com/v1/tracks/3DWDcsDoXRIF...,https://api.spotify.com/v1/audio-analysis/3DWD...,184627,4
97,0.767,0.659,7,-4.541,1,0.0387,0.7850,0.000000,0.1120,0.631,90.056,audio_features,6fmtZEUoGwxPNvUgr0NJm1,spotify:track:6fmtZEUoGwxPNvUgr0NJm1,https://api.spotify.com/v1/tracks/6fmtZEUoGwxP...,https://api.spotify.com/v1/audio-analysis/6fmt...,186720,4
98,0.752,0.468,0,-9.966,1,0.3330,0.8050,0.000000,0.1360,0.716,82.795,audio_features,2edc1m7WXxdBA61WlxSInp,spotify:track:2edc1m7WXxdBA61WlxSInp,https://api.spotify.com/v1/tracks/2edc1m7WXxdB...,https://api.spotify.com/v1/audio-analysis/2edc...,179253,4
99,0.797,0.654,8,-7.373,1,0.2450,0.6330,0.000000,0.1060,0.640,145.121,audio_features,3qjDXaWCalJ9ZzaHBG4j3V,spotify:track:3qjDXaWCalJ9ZzaHBG4j3V,https://api.spotify.com/v1/tracks/3qjDXaWCalJ9...,https://api.spotify.com/v1/audio-analysis/3qjD...,172520,4

In [6]:
df_musics.dtypes

danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
type                 object
id                   object
uri                  object
track_href           object
analysis_url         object
duration_ms           int64
time_signature        int64
dtype: object

In [7]:
df_musics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   danceability      100 non-null    float64
 1   energy            100 non-null    float64
 2   key               100 non-null    int64
 3   loudness          100 non-null    float64
 4   mode              100 non-null    int64
 5   speechiness       100 non-null    float64
 6   acousticness      100 non-null    float64
 7   instrumentalness  100 non-null    float64
 8   liveness          100 non-null    float64
 9   valence           100 non-null    float64
 10  tempo             100 non-null    float64
 11  type              100 non-null    object
 12  id                100 non-null    object
 13  uri               100 non-null    object
 14  track_href        100 non-null    object
 15  analysis_url      100 non-null    object
 16  duration_ms       100 non-null    int64
 17  time_signature    100 non-null    int64
dtypes: float64(9), int64(4), object(5)
memory usage: 14.2+ KB

In [8]:
path + "/athletes.csv"

'C:/Users/bianc/OneDrive/Documents/1-Estudos/2-DNC/1-Data Science/1-Material/Materis8-DataCleaning_Wrangling/MichineLearning/DataCW-main/DataCW-main/Datasets/athletes.csv'

In [9]:
df_athletes = pd.read_csv(path + "/athletes.csv")
df_athletes

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,JOSEPH E,Elijah JOSEPH,Male,Athlete,TTO,Trinidad and Tobago,Trinidad and Tobago,Trinidad and Tobago,...,NaN,English,Personal: Ebert Joseph (TTO),NaN,NaN,NaN,NaN,NaN,NaN,NaN
11106,4982762,HOMAN Khrystyna,HOMAN K,Khrystyna HOMAN,Female,Athlete,UKR,Ukraine,Ukraine,Ukraine,...,Mother and one younger brother,Ukrainian,National: Quedjau Nhabali (UKR).<br>Personal: ...,Because her mother raised the idea,NaN,"""Quedjau Nhabali is always there with the righ...",NaN,NaN,NaN,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,CHELANGAT AC,Annet Chemengich CHELANGAT,Female,Athlete,UGA,Uganda,Uganda,Uganda,...,NaN,English,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11108,4986655,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,NaN,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_athletes.dtypes

code                    int64
name                   object
name_short             object
name_tv                object
gender                 object
function               object
country_code           object
country                object
country_full           object
nationality            object
nationality_full       object
nationality_code       object
height                  int64
weight                float64
disciplines            object
events                 object
birth_date             object
birth_place            object
birth_country          object
residence_place        object
residence_country      object
nickname               object
hobbies                object
occupation             object
education              object
family                 object
lang                   object
coach                  object
reason                 object
hero                   object
influence              object
philosophy             object
sporting_relatives     object
ritual                 object
other_sports           object
dtype: object

In [11]:
df_athletes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11110 entries, 0 to 11109
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   code                11110 non-null  int64
 1   name                11110 non-null  object
 2   name_short          11110 non-null  object
 3   name_tv             11110 non-null  object
 4   gender              11110 non-null  object
 5   function            11110 non-null  object
 6   country_code        11110 non-null  object
 7   country             11110 non-null  object
 8   country_full        11110 non-null  object
 9   nationality         11091 non-null  object
 10  nationality_full    11091 non-null  object
 11  nationality_code    11091 non-null  object
 12  height              11110 non-null  int64
 13  weight              11092 non-null  float64
 14  disciplines         11110 non-null  object
 15  events              11110 non-null  object
 16  birth_date          11110 non-null  object
 17  birth_place         8713 non-null   object
 18  birth_country       9461 non-null   object
 19  residence_place     6792 non-null   object
 20  residence_country   8276 non-null   object
 21  nickname            2963 non-null   object
 22  hobbies             4201 non-null   object
 23  occupation          9571 non-null   object
 24  education           5531 non-null   object
 25  family              5555 non-null   object
 26  lang                10588 non-null  object
 27  coach               8212 non-null   object
 28  reason              5838 non-null   object
 29  hero                3312 non-null   object
 30  influence           2151 non-null   object
 31  philosophy          2779 non-null   object
 32  sporting_relatives  2516 non-null   object
 33  ritual              856 non-null    object
 34  other_sports        1057 non-null   object
dtypes: float64(1), int64(2), object(32)
memory usage: 3.0+ MB

In [12]:
df_athletes["code"].astype(str)

0        1532872
1        1532873
2        1532874
3        1532944
4        1532945
          ...
11105    4982175
11106    4982762
11107    4983537
11108    4986655
11109    9460001
Name: code, Length: 11110, dtype: object

In [13]:
pd.to_datetime(df_athletes["birth_date"])

0       1991-10-21
1       1999-01-22
2       1996-12-21
3       1999-11-22
4       1999-10-27
           ...
11105   2001-07-03
11106   1999-01-31
11107   1993-07-29
11108   2003-06-11
11109   2000-04-27
Name: birth_date, Length: 11110, dtype: datetime64[ns]

## Filtando dados:

In [15]:
df_athletes[df_athletes["country_full"] == "Brazil"]

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
1413,1561237,CARDOSO Adriana,CARDOSO A,Adriana CARDOSO,Female,Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,"Portuguese, Spanish",National: Cristiano Silva (BRA).<br>Club: Boja...,NaN,NaN,NaN,"""If you obey all the rules you will miss all t...",NaN,NaN,NaN
1414,1561239,BOLZAN Ana Claudia,BOLZAN AC,Ana Claudia BOLZAN,Female,Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,"English, Portuguese",National: Cristiano Silva (BRA),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1415,1561242,ARENHART Barbara,ARENHART B,Barbara ARENHART,Female,Alternate Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,"English, German, Portuguese, Spanish",National: Cristiano Silva (BRA).<br>Club: Drag...,NaN,"Basketball player Oscar Schmidt (BRA), five-ti...",NaN,"""This too shall pass."" (myInfo)",NaN,NaN,NaN
1416,1561243,de PAULA Bruna,de PAULA B,Bruna de PAULA,Female,Athlete,BRA,Brazil,Brazil,Brazil,...,"Mother, Marinalva. Four sisters","French, Portuguese",National: Cristiano Silva (BRA).<br>Club: Per ...,"Played football in her younger years, but swit...","Footballer Neymar (BRA), two-time Olympic meda...",Her mother,NaN,NaN,NaN,NaN
1417,1561248,BITOLO Gabriela,BITOLO G,Gabriela BITOLO,Female,Athlete,BRA,Brazil,Brazil,Brazil,...,"Partner, Gaston Mourino",Portuguese,National: Cristiano Silva (BRA).<br>Club: Suso...,NaN,NaN,NaN,NaN,"Partner, Gaston Mourino (handball), Tokyo 2020...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9985,1968115,PESSOA Rodrigo,PESSOA R,Rodrigo PESSOA,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9986,1968116,FONSECA Ruy,FONSECA R,Ruy FONSECA,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Renata. Daughters, Carolina and Cecilia","English, French, Italian, Portuguese, Spanish",William Fox-Pitt (GBR),"His parents were riders, so he following them ...",NaN,His parents,NaN,"Wife, Renata Rabello Costa (equestrian), bronz...",NaN,NaN
9987,1968118,de FREITAS BARCHA Stephan,BARCHA Stephan,Stephan de FREITAS BARCHA,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Roberta Milani. One son. Two daughters",English,NaN,“My father had a farm in the countryside where...,"Equestrian show jumper Ludger Beerbaum (GER), ...","His parents, and coaches, Nelson Pessoa (BRA) ...","""I learn from defeats, not from victories."" (C...","Wife, Roberta Milani (equestrian), has served ...",NaN,NaN
9988,1968125,MANSUR Yuri,MANSUR Y,Yuri MANSUR,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Louise. Children, Pedro and Marie Louise","English, French, Portuguese",NaN,He was not from a family that had horses or co...,Equestrian show jumpers:<br>Nelson Pessoa (BRA...,Brazilian rider Nelson Pessoa,"""My strongest quality, in everything I do, is ...",NaN,NaN,NaN
10951,3430817,SCHEFFER Fernando,SCHEFFER F,Fernando SCHEFFER,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,Portuguese,"Club: Fernando Possenti (BRA), since September...","Followed his brother into the sport. ""My broth...","Swimmer Kaio Almeida (BRA), four-time Olympian...",NaN,"""Never give up your dreams."" (myInfo)",NaN,"""I don’t listen to music behind the blocks or ...",NaN

In [16]:
df_brazil = df_athletes[df_athletes["country_full"] == "Brazil"]

In [17]:
df_brazil.shape

(290, 35)

In [18]:
df_brazil[df_brazil["nationality"] != "Brazil"]

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
9980,1968081,PARRO Carlos,PARRO C,Carlos PARRO,Male,Alternate Athlete,BRA,Brazil,Brazil,Italy,...,"Wife, Nicola. Son, Luca. Daughter, Margot","English, Portuguese",National (jumping): Mark Todd (NZL).<br>Person...,He developed an interest in horses while stayi...,"Equestrian eventing rider Mark Todd (NZL), six...",NaN,NaN,"Older brother, Andre Parro (equestrian), repre...",NaN,NaN

In [19]:
df_athletes[df_athletes["country_full"] != "Brazil"]

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
0,1532872,ALEKSANYAN Artur,ALEKSANYAN A,Artur ALEKSANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Father, Gevorg Aleksanyan","Armenian, English, Russian","Gevorg Aleksanyan (ARM), father",He followed his father and his uncle into the ...,"Footballer Zinedine Zidane (FRA), World Cup wi...","His father, Gevorg Aleksanyan","""Wrestling is my life."" (mediamax.am. 18 May 2...",NaN,NaN,NaN
1,1532873,AMOYAN Malkhas,AMOYAN M,Malkhas AMOYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,NaN,NaN,NaN,NaN,"""To become a good athlete, you first have to b...","Uncle, Roman Amoyan (wrestling), 2008 Olympic ...",NaN,NaN
2,1532874,GALSTYAN Slavik,GALSTYAN S,Slavik GALSTYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,NaN,Armenian,Personal: Martin Alekhanyan (ARM).<br>National...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1532944,HARUTYUNYAN Arsen,HARUTYUNYAN A,Arsen HARUTYUNYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Diana (married October 2022). Daughter, ...",Armenian,National: Habetnak Kurghinyan,While doing karate he noticed wrestlers traini...,"Wrestler Armen Nazaryan (ARM, BUL), two-time O...",NaN,"“Nothing is impossible, set goals in front of ...",NaN,NaN,NaN
4,1532945,TEVANYAN Vazgen,TEVANYAN V,Vazgen TEVANYAN,Male,Athlete,ARM,Armenia,Armenia,Armenia,...,"Wife, Sona (married November 2023)","Armenian, Russian",National: Habetnak Kurghinyan (ARM),“My family did not like wrestling very much. A...,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11105,4982175,JOSEPH Elijah,JOSEPH E,Elijah JOSEPH,Male,Athlete,TTO,Trinidad and Tobago,Trinidad and Tobago,Trinidad and Tobago,...,NaN,English,Personal: Ebert Joseph (TTO),NaN,NaN,NaN,NaN,NaN,NaN,NaN
11106,4982762,HOMAN Khrystyna,HOMAN K,Khrystyna HOMAN,Female,Athlete,UKR,Ukraine,Ukraine,Ukraine,...,Mother and one younger brother,Ukrainian,National: Quedjau Nhabali (UKR).<br>Personal: ...,Because her mother raised the idea,NaN,"""Quedjau Nhabali is always there with the righ...",NaN,NaN,NaN,She likes MMA
11107,4983537,CHELANGAT Annet Chemengich,CHELANGAT AC,Annet Chemengich CHELANGAT,Female,Athlete,UGA,Uganda,Uganda,Uganda,...,NaN,English,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11108,4986655,ADA ETO Sefora,ADA ETO S,Sefora ADA ETO,Female,Athlete,GEQ,Equatorial Guinea,Equatorial Guinea,Equatorial Guinea,...,NaN,Spanish,Personal: Feliciano Javier y Mananses Mba Micha,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11109,9460001,LIUZZI Emanuela,LIUZZI E,Emanuela LIUZZI,Female,Athlete,ITA,Italy,Italy,NaN,...,NaN,Italian,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_athletes[df_athletes["country_full"].isin(["Brazil", "Argentina"]) ]

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
101,1535729,SERRANO Franco,SERRANO F,Franco SERRANO,Male,Athlete,ARG,Argentina,Argentina,Argentina,...,NaN,Spanish,NaN,NaN,NaN,His family,"""The reward is always greater than any effort....",NaN,NaN,NaN
199,1537180,CEBALLOS Macarena,CEBALLOS M,Macarena CEBALLOS,Female,Athlete,ARG,Argentina,Argentina,Argentina,...,"Father, Claudio. Mother, Liliana Giacomelli (d...",Spanish,National: Gustavo Roldan,Older sister started swimming. “I was very att...,"Swimmer Michael Phelps (USA), 28-time Olympic ...",NaN,"""Stand up and Fight"" is tattooed on her left arm",NaN,NaN,NaN
208,1537209,HEIN Agostina,HEIN A,Agostina HEIN,Female,Athlete,ARG,Argentina,Argentina,Argentina,...,NaN,Spanish,Club: Sebastian Montero,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,1537465,SARAVIA Ulises,SARAVIA U,Ulises SARAVIA,Male,Athlete,ARG,Argentina,Argentina,Argentina,...,NaN,Spanish,Federico Diez Andersen,NaN,"Footballer Lionel Messi (ARG), FIFA World Cup ...",NaN,NaN,NaN,NaN,NaN
231,1537510,BORELLI Florencia,BORELLI F,Florencia BORELLI,Female,Athlete,ARG,Argentina,Argentina,Argentina,...,"Husband, Facundo. Son, Milo (born 2015). Fathe...",Spanish,Personal: Fernando Diaz Sanchez (ARG),NaN,NaN,NaN,NaN,"Twin sister Mariana (athletics), two-time Sout...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,1968116,FONSECA Ruy,FONSECA R,Ruy FONSECA,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Renata. Daughters, Carolina and Cecilia","English, French, Italian, Portuguese, Spanish",William Fox-Pitt (GBR),"His parents were riders, so he following them ...",NaN,His parents,NaN,"Wife, Renata Rabello Costa (equestrian), bronz...",NaN,NaN
9987,1968118,de FREITAS BARCHA Stephan,BARCHA Stephan,Stephan de FREITAS BARCHA,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Roberta Milani. One son. Two daughters",English,NaN,“My father had a farm in the countryside where...,"Equestrian show jumper Ludger Beerbaum (GER), ...","His parents, and coaches, Nelson Pessoa (BRA) ...","""I learn from defeats, not from victories."" (C...","Wife, Roberta Milani (equestrian), has served ...",NaN,NaN
9988,1968125,MANSUR Yuri,MANSUR Y,Yuri MANSUR,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,"Wife, Louise. Children, Pedro and Marie Louise","English, French, Portuguese",NaN,He was not from a family that had horses or co...,Equestrian show jumpers:<br>Nelson Pessoa (BRA...,Brazilian rider Nelson Pessoa,"""My strongest quality, in everything I do, is ...",NaN,NaN,NaN
10951,3430817,SCHEFFER Fernando,SCHEFFER F,Fernando SCHEFFER,Male,Athlete,BRA,Brazil,Brazil,Brazil,...,NaN,Portuguese,"Club: Fernando Possenti (BRA), since September...","Followed his brother into the sport. ""My broth...","Swimmer Kaio Almeida (BRA), four-time Olympian...",NaN,"""Never give up your dreams."" (myInfo)",NaN,"""I don’t listen to music behind the blocks or ...",NaN
10987,3556435,SIMEONE Giuliano,SIMEONE G,Giuliano SIMEONE,Male,Athlete,ARG,Argentina,Argentina,Argentina,...,"Father, Diego Simeone (born 1970). Older broth...","Italian, Spanish",Club: Diego Simeone (ARG/ITA).<br>National: Ja...,NaN,NaN,NaN,NaN,"Father, Diego Simeone (football), played for a...",NaN,NaN

In [23]:
df_athletes[df_athletes["height"] >= 200]

,code,name,name_short,name_tv,gender,function,country_code,country,country_full,nationality,...,family,lang,coach,reason,hero,influence,philosophy,sporting_relatives,ritual,other_sports
399,1540143,FISCHER Guillermo,FISCHER G,Guillermo FISCHER,Male,Athlete,ARG,Argentina,Argentina,Argentina,...,"Father, Rodolfo ""Lobo"" Fischer (deceased 2020)...",Spanish,National: Guillermo Milano (ARG).<br>Club: Jac...,NaN,NaN,NaN,NaN,"Father, Rodolfo ""Lobo"" Fischer (football), pla...",NaN,NaN
701,1544444,RAFTERY Jack,RAFTERY J,Jack RAFTERY,Male,Alternate Athlete,IRL,Ireland,Ireland,Ireland,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1091,1552386,FABBRI Leonardo,FABBRI L,Leonardo FABBRI,Male,Athlete,ITA,Italy,Italy,Italy,...,"Father, Fabio",Italian,Personal: Paolo Dal Soglio (ITA),Comes from a sporting family. His father was a...,"Shot putter David Storl (GER), 2012 Olympic si...",NaN,NaN,"Father, Fabio (athletics), 100m personal best:...",NaN,NaN
1244,1556225,COLODROVSCHI Silvian,COLODROVSCHI S,Silvian COLODROVSCHI,Male,Athlete,ROU,Romania,Romania,Romania,...,NaN,"French, Romanian",National: Bogdan Rath (ROU),NaN,NaN,NaN,NaN,NaN,NaN,NaN
1248,1556230,IUDEAN Francesco,IUDEAN F,Francesco IUDEAN,Male,Athlete,ROU,Romania,Romania,Romania,...,NaN,Romanian,National: Bogdan Rath (ROU),NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10880,1981495,MOZIC Rok,MOZIC R,MOZIC,Male,Athlete,SLO,Slovenia,Slovenia,Slovenia,...,"Father, Peter","English, Slovenian",National: Gheorghe Cretu (ROU),Took up volleyball because his parents played,"Volleyball player Wilfredo Leon (CUB/POL), 202...",NaN,NaN,NaN,Eats three hours before a match and then naps....,Beach volleyball: Represented Slovenia at yout...
10882,1981504,STALEKAR Saso,STALEKAR S,STALEKAR,Male,Athlete,SLO,Slovenia,Slovenia,Slovenia,...,NaN,Slovenian,National: Gheorghe Cretu (ROU),"Started playing handball, but his club went ba...","Basketball player Lebron James (USA), four-tim...",NaN,NaN,NaN,NaN,NaN
10889,1981540,URNAUT Tine,URNAUT T,URNAUT,Male,Athlete,SLO,Slovenia,Slovenia,Slovenia,...,"Father, Adolf. Mother, Anita. Older brothers, ...",Slovenian,National: Gheorghe Cretu (ROU),Took up volleyball because his family played,NaN,NaN,NaN,"Father, Adolf Urnaut (volleyball), represented...",NaN,Beach volleyball: Has competed for Slovenia
10892,1981548,STERN Toncek,STERN T,T. STERN,Male,Athlete,SLO,Slovenia,Slovenia,Slovenia,...,"Sons, Toncek and Jakob. Father, Anton. Mother,...",Slovenian,National: Gheorghe Cretu (ROU),Took up volleyball after watching others play ...,NaN,NaN,NaN,"Brother, Ziga Stern (volleyball), also represe...",NaN,NaN
10895,1981556,KASTELIC Urh,KASTELIC U,Urh KASTELIC,Male,Athlete,SLO,Slovenia,Slovenia,Slovenia,...,NaN,Slovenian,National: Uros Zorman (SLO).<br>Club: Florian ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
df_athletes[df_athletes["height"] >= 200].shape

(254, 35)

In [ ]:
df[]